swagger: '2.0'
info:
  version: '0.1.0'
  title: Boozify Encyclopedia
  description: An API to interact with a encyclopedia about beers and the companies that make them
host: localhost:8070
basePath: /api
schemes:
  - http
paths:
  /beers:
    post:
      description: create a beer
      operationId: createBeer
      consumes:
        - application/json
      parameters:
        - name: beer
          in: body
          required: true
          schema:
            $ref: '#/definitions/Beer'
      responses:
        '201':
          description: created
          schema:
            type: object

  /beers/{name}:
    get:
      description: get a beer
      operationId: getBeer
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Beer'

  /companies:
    post:
      description: create a company
      operationId: createCompany
      consumes:
        - application/json
      parameters:
        - name: company
          in: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: created
          schema:
            type: object

  /company/{name}:
     get:
       description: get a company
       operationId: getCompany
       produces:
         - application/json
       parameters:
         - name: name
           in: path
           required: true
           type: string
       responses:
         '200':
           description: success
           schema:
             $ref: '#/definitions/Company'

definitions:
  Beer:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      alcohol:
        type: integer

  Company:
    type: object
    properties:
      name:
        type: string
      address:
        type: string