swagger: '2.0'
info:
  version: '0.1.0'
  title: Boozify Encyclopedia
  description: An API to interact with a encyclopedia about beers and the companies that make them
host: localhost:8070
basePath: /api
schemes:
  - http
paths:
  /beers:
    post:
      description: create a beer
      operationId: createBeer
      consumes:
        - application/json
      parameters:
        - name: beer
          in: body
          required: true
          schema:
            $ref: '#/definitions/Beer'
      responses:
        '201':
          description: beer created
          schema:
            type: object
    get:
      description: get a list of all beers
      operationId: getBeers
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Beer'

  /beers/{name}:
    get:
      description: get a beer
      operationId: getBeer
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Beer'
    patch:
      description: update a beer's information
      operationId: updateBeer
      consumes:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: beer
          in: body
          required: true
          schema:
            $ref: '#/definitions/Beer'
      responses:
        '201':
          description: beer updated
    delete:
      description: delete a beer from the encyclopedia
      operationId: deleteBeer
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        "204":
          description: beer deleted

  /companies:
    post:
      description: create a company
      operationId: createCompany
      consumes:
        - application/json
      parameters:
        - name: company
          in: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: company created
          schema:
            type: object
    get:
      description: get a list of all companies
      operationId: getCompanies
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'

  /companies/{name}:
     get:
       description: get a company
       operationId: getCompany
       produces:
         - application/json
       parameters:
         - name: name
           in: path
           required: true
           type: string
       responses:
         '200':
           description: success
           schema:
             $ref: '#/definitions/Company'
     patch:
       description: update a company's information
       operationId: updateCompany
       consumes:
         - application/json
       parameters:
         - name: name
           in: path
           required: true
           type: string
         - name: company
           in: body
           required: true
           schema:
             $ref: '#/definitions/Company'
       responses:
         '201':
           description: company updated
     delete:
       description: delete a company from the encyclopedia
       operationId: deleteCompany
       parameters:
         - name: name
           in: path
           required: true
           type: string
       responses:
         "204":
           description: company deleted

definitions:
  Beer:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      alcohol:
        type: integer

  Company:
    type: object
    properties:
      name:
        type: string
      address:
        type: string